version: '3'

services:
  cache:
    image: redis:6.0.5

  txsentinel-web:
    image: txsentinel:latest
    env_file:
      - ./txsentinel.env
    command: flask run -h 0.0.0.0 -p 5000
    ports:
      - "5000:5000"
    volumes:
      - ./txsentinel:/home/sentinel/txsentinel
      - ./tests:/home/sentinel/tests
    depends_on:
      - cache

  txsentinel-worker:
    image: txsentinel:latest
    env_file:
      - ./txsentinel.env
    command: celery --app txsentinel worker --loglevel INFO
    volumes:
      - ./txsentinel:/home/sentinel/txsentinel
      - ./tests:/home/sentinel/tests
    depends_on:
      - cache
