apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tx.secretName" . }}
  labels:
{{ include "tx.commonLabels" . | indent 4 }}
    app.kubernetes.io/component: app-secret
type: Opaque
data:
  {{- range $name, $value := .Values.secrets }}
  {{ $name }}: {{ $value }}
  {{- end }}
