apiVersion: v1
kind: Service
metadata:
  name: {{ include "tx.webName" . }}
  labels:
{{ include "tx.commonLabels" . | indent 4 }}
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  ports:
    - name: web-http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: web
