{{- if .Values.serviceAccount.create -}}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tx.serviceAccountName" . }}
  labels:
{{ include "tx.commonLabels" . | indent 4 }}
    app.kubernetes.io/component: app-service-account

{{- end -}}
